### ISSUE TITLE
Selectting a body (Eeloo) as the origin, and one of a planet's moon's (say one of Juul's) changes the origin to Kerbin

### ISSUE THREAD

**Issue by havidad** [LoicViennois/KSP-DeltaV-Planner#5]
Essentially there is no way for you to map a journey where, from on your way back from Eeloo, you stop at juul and one of the moon's, for example.

**Comment by LoicViennois** [comment]
The map is designed for interplanetary travels **from** or **to** Kerbin, it is not meant to be used for interplanetary travels between two bodies other than Kerbin.
To compute DeltaV between two bodies other than Kerbin, it would be necessary to have a simulation tool like this one : https://alexmoon.github.io/ksp/
I definitely plan to add such a tool in my app, but it is still a work in progress.
Hope you find it useful anyway.
